
project_id = "xjhhehxcxkiumnwbirel"

[global.env]
TELEGRAM_BOT_TOKEN = "env(TELEGRAM_BOT_TOKEN)"
OPENAI_API_KEY = "env(OPENAI_API_KEY)"
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"
NODE_ENV = "env(NODE_ENV)"
APP_ENV = "env(APP_ENV)"

# Default settings for all functions
[global]
verify_jwt = false  # Default to no JWT verification, enable on per-function basis for protected routes
memory = 256  # Default memory allocation (in MB)
timeout = 60  # Default timeout (in seconds)
runtime = "edge"  # Use Edge runtime for optimal performance

# Function-specific overrides can be done in individual config.toml files
