
project_id = "xjhhehxcxkiumnwbirel"

[global.env]
TELEGRAM_BOT_TOKEN = "env(TELEGRAM_BOT_TOKEN)"
OPENAI_API_KEY = "env(OPENAI_API_KEY)"
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"

# Default settings for all functions
[global]
verify_jwt = false  # Default to no JWT verification, enable on per-function basis for protected routes

# Function-specific overrides can be added below
# Example:
# [functions.user-protected-function]
# verify_jwt = true
