project_id = "xjhhehxcxkiumnwbirel"
base_url = "https://xjhhehxcxkiumnwbirel.supabase.co"

[global.env]
TELEGRAM_BOT_TOKEN = "env(TELEGRAM_BOT_TOKEN)"
OPENAI_API_KEY = "env(OPENAI_API_KEY)"
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"
NODE_ENV = "env(NODE_ENV)"
APP_ENV = "env(APP_ENV)"

# Public-facing webhook functions - no JWT verification
[functions.telegram-webhook]
verify_jwt = false
[functions.log-operation]
verify_jwt = false
[functions.xdelo_caption_parser]
verify_jwt = false
[functions.xdelo_delete_message]
verify_jwt = false

# User-authenticated functions
[functions.user-data]
verify_jwt = false
[functions.create-ayd-session]
verify_jwt = false

# Other utility functions
[functions.product-matching]
verify_jwt = false
[functions.unified-logging]
verify_jwt = false

# Note: The following functions have been removed or consolidated:
# - manual-caption-parser (consolidated into xdelo_caption_parser)
# - direct-caption-processor (consolidated into xdelo_caption_parser)
# - update-telegram-caption (removed)
# - process-audio-upload (removed)
# - validate-storage-files (removed)
