
project_id = "xjhhehxcxkiumnwbirel"
base_url = "https://xjhhehxcxkiumnwbirel.supabase.co"

[global.env]
TELEGRAM_BOT_TOKEN = "env(TELEGRAM_BOT_TOKEN)"
OPENAI_API_KEY = "env(OPENAI_API_KEY)"
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"
NODE_ENV = "env(NODE_ENV)"
APP_ENV = "env(APP_ENV)"

# Public-facing webhook functions - no JWT verification
[functions.telegram-webhook]
verify_jwt = false
[functions.log-operation]
verify_jwt = false
[functions.manual-caption-parser]
verify_jwt = false
[functions.update-telegram-caption]
verify_jwt = false
[functions.direct-caption-processor]
verify_jwt = false

# User-authenticated functions
[functions.user-data]
verify_jwt = true
[functions.create-ayd-session]
verify_jwt = true
[functions.validate-storage-files]
verify_jwt = true

# Other utility functions
[functions.cleanup-storage-on-delete]
verify_jwt = false
[functions.direct-caption-processor]
verify_jwt = false
[functions.generic-webhook]
verify_jwt = false
[functions.media-management]
verify_jwt = false
[functions.process-audio-upload]
verify_jwt = false
[functions.product-matching]
verify_jwt = false
[functions.xdelo_delete_message]
verify_jwt = false
