
# A string used as a project reference when generating edge functions locally
project_id = "xjhhehxcxkiumnwbirel"

[functions.analyze-with-ai]
verify_jwt = false
[functions.create-analyze-message-caption]
verify_jwt = false

[functions.delete-telegram-message]
verify_jwt = false

[functions.generic-webhook]
verify_jwt = false

[functions.openai-request]
verify_jwt = false

[functions.parse-caption-with-ai]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.xdelo_sync_media_group]
verify_jwt = false

[functions.user-data]
verify_jwt = false

[functions.xdelo_file_repair]
verify_jwt = false

# New, consolidated file repair function
[functions.xdelo_standardize_storage_paths]
verify_jwt = false

# Cleanup unnecessary or deprecated functions
# [functions.process-unanalyzed-messages]
# [functions.repair-storage-paths]
# [functions.redownload-from-media-group]
# [functions.fix-file-ids]
# [functions.scheduler-process-queue]
