
# Supabase configuration file
# This is the main config file for Supabase CLI

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[realtime]
enabled = true

[storage]
enabled = true

[functions]

[functions.analyze-with-ai]
verify_jwt = false

[functions.cleanup-storage-on-delete]
verify_jwt = false

[functions.create-ayd-session]
verify_jwt = false

[functions.delete-telegram-message]
verify_jwt = false

[functions.log-operation]
verify_jwt = false

[functions.parse-caption-with-ai]
verify_jwt = false

[functions.process-audio-upload]
verify_jwt = false

[functions.process-unanalyzed-messages]
verify_jwt = false

[functions.product-matching]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.update-telegram-caption]
verify_jwt = false