project_id = "xjhhehxcxkiumnwbirel"

[functions.analyze-with-ai]
verify_jwt = false
[functions.cleanup-storage-on-delete]
verify_jwt = false
[functions.create-analyze-message-caption]
verify_jwt = false
[functions.create-ayd-session]
verify_jwt = false
[functions.delete-telegram-message]
verify_jwt = false
[functions.generic-webhook]
verify_jwt = false
[functions.log-operation]
verify_jwt = false
[functions.openai-request]
verify_jwt = false
[functions.product-matching]
verify_jwt = false
[functions.telegram-webhook]
verify_jwt = false
[functions.update-telegram-caption]
verify_jwt = false

# Consolidated functions
[functions.message-processor]
verify_jwt = false
[functions.media-processor]
verify_jwt = false

# Removed deprecated functions:
# - manual-caption-parser (consolidated into message-processor)
# - parse-caption-with-ai (consolidated into message-processor)
# - repair-media (consolidated into media-processor)
# - media-management (consolidated into media-processor)
# - validate-storage-files (consolidated into media-processor)
