project_id = "xjhhehxcxkiumnwbirel"

[functions.cleanup-storage-on-delete]
verify_jwt = false
[functions.create-ayd-session]
verify_jwt = false
[functions.delete-telegram-message]
verify_jwt = false
[functions.product-matching]
verify_jwt = false
[functions.telegram-webhook]
verify_jwt = false
[functions.update-telegram-caption]
verify_jwt = false

