project_id = "xjhhehxcxkiumnwbirel"
base_url = "https://xjhhehxcxkiumnwbirel.supabase.co"
[functions.analyze-with-ai]
verify_jwt = false
[functions.create-analyze-message-caption]
verify_jwt = false
[functions.delete-telegram-message]
verify_jwt = false
[functions.generic-webhook]
verify_jwt = false
[functions.openai-request]
verify_jwt = false
[functions.parse-caption-with-ai]
verify_jwt = false
[functions.process-unanalyzed-messages]
verify_jwt = false
[functions.scheduler-process-queue]
verify_jwt = false
[functions.telegram-webhook]
verify_jwt = false
[functions.xdelo_sync_media_group]
verify_jwt = false
[functions.user-data]
verify_jwt = false

