# Config for the webhook setup function
project_id = "xjhhehxcxkiumnwbirel"
name = "xdelo_set-telegram-webhook"
version = 1
path = "xdelo_set-telegram-webhook"

# Explicitly disable JWT verification
verify_jwt = false

# Allow API calls to Telegram
allowed_http_hosts = ["api.telegram.org", "*"] 