
# This configuration file sets the behavior and permissions for the direct-caption-processor function

name = "direct-caption-processor"
template = "typescript"
memory = 1024 # Higher memory (1 GB) since we're doing multiple operations
verify_jwt = false # Not requiring JWT as this is triggered directly from database
entrypoint = "/index.ts"
# This function should be triggered directly from database events

[experimental.migrations]
create = "ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'direct_caption_processor_success';\nALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'direct_caption_processor_error';"

[triggers]
database_messages_insert = "INSERT ON messages WHERE caption IS NOT NULL AND caption != ''"
database_messages_update = "UPDATE OF caption ON messages WHERE caption IS NOT NULL AND caption != ''"

[hooks]
function_path = "/supabase/functions/direct-caption-processor"
