export enum LogEventType {
  // System operations
  SYSTEM_STARTUP = "SYSTEM_STARTUP",
  SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN",
  SYSTEM_ERROR = "SYSTEM_ERROR",
  SYSTEM_REPAIR = "SYSTEM_REPAIR",
  SYSTEM_CONFIG_CHANGE = "SYSTEM_CONFIG_CHANGE",
  SYSTEM_WARNING = "SYSTEM_WARNING",
  SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE",
  
  // User actions
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_REGISTER = "USER_REGISTER",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_PASSWORD_RESET = "USER_PASSWORD_RESET",
  USER_ACTION = "USER_ACTION",
  
  // Message operations
  MESSAGE_CREATED = "MESSAGE_CREATED",
  MESSAGE_UPDATED = "MESSAGE_UPDATED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_REPROCESSED = "MESSAGE_REPROCESSED",
  MESSAGE_PROCESSED = "MESSAGE_PROCESSED",
  
  // Media operations
  MEDIA_UPLOAD = "MEDIA_UPLOAD",
  MEDIA_DOWNLOAD = "MEDIA_DOWNLOAD",
  MEDIA_DELETE = "MEDIA_DELETE",
  MEDIA_REPAIR = "MEDIA_REPAIR",
  MEDIA_GROUP_SYNC = "MEDIA_GROUP_SYNC",
  MEDIA_GROUP_FETCH = "MEDIA_GROUP_FETCH",
  MEDIA_REPAIR_STARTED = "MEDIA_REPAIR_STARTED",
  MEDIA_REPAIR_COMPLETED = "MEDIA_REPAIR_COMPLETED",
  MEDIA_REPAIR_FAILED = "MEDIA_REPAIR_FAILED",
  
  // Telegram operations
  TELEGRAM_WEBHOOK = "TELEGRAM_WEBHOOK",
  TELEGRAM_BOT_UPDATE = "TELEGRAM_BOT_UPDATE",
  TELEGRAM_MESSAGE_DELETE = "TELEGRAM_MESSAGE_DELETE",
  
  // Processing operations
  PROCESSING_STATE_CHANGED = "PROCESSING_STATE_CHANGED",
  CAPTION_ANALYZED = "CAPTION_ANALYZED",
  CAPTION_PARSED = "CAPTION_PARSED",
  
  // Sync operations
  SYNC_STARTED = "SYNC_STARTED",
  SYNC_COMPLETED = "SYNC_COMPLETED",
  SYNC_FAILED = "SYNC_FAILED",
  SYNC_PRODUCTS = "SYNC_PRODUCTS",
  
  // API operations
  API_REQUEST = "API_REQUEST",
  API_RESPONSE = "API_RESPONSE",
  API_ERROR = "API_ERROR",
  
  // Other operations
  STORAGE_OPERATION = "STORAGE_OPERATION",
  DATABASE_OPERATION = "DATABASE_OPERATION"
}
