create table public.gl_products (
  id uuid not null default gen_random_uuid (),
  glide_row_id text null,
  rowid_accounts text null,
  rowid_vendor_payments text null,
  rowid_purchase_orders text null,
  purchase_order_uid text null,
  po_po_date timestamp with time zone null,
  vendor_product_name text null,
  new_product_name text null,
  product_purchase_date timestamp with time zone null,
  total_qty_purchased numeric null,
  cost numeric null,
  samples_or_fronted boolean null,
  fronted boolean null,
  terms_for_fronted_product text null,
  samples boolean null,
  total_units_behind_sample numeric null,
  purchase_notes text null,
  miscellaneous_items boolean null,
  category text null,
  product_image1 text null,
  date_timestamp_subm timestamp with time zone null,
  email_email_of_user_who_added_product text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  display_name text GENERATED ALWAYS as (COALESCE(new_product_name, vendor_product_name)) STORED null,
  constraint gl_products_pkey primary key (id),
  constraint gl_products_glide_row_id_key unique (glide_row_id)
) TABLESPACE pg_default;
