// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovpsyrhigencvzlxqwqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cHN5cmhpZ2VuY3Z6bHhxd3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMjg2NzYsImV4cCI6MjA1MzcwNDY3Nn0.OCWxq7ndhbi1VBZIVMs6gopW05bhE5a6EH8V6KqzMMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);