
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjhhehxcxkiumnwbirel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqaGhlaHhjeGtpdW1ud2JpcmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNDYwMjIsImV4cCI6MjA1MzcyMjAyMn0.ibZQd1XNtfa3zq-uzRmA8AEvxAy6Cjs22S7yb736xPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
