
project_id = "xjhhehxcxkiumnwbirel"
name = "xdelo_standardize_urls"
description = "Standardizes public URLs for media files"
version = 1
verify_jwt = true

[functions.xdelo_standardize_urls.jwt]
optional = true
